//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWinsowsForm.proxyDuenio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxyDuenio.IDuenioService")]
    public interface IDuenioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuenioService/RegistrarDuenio", ReplyAction="http://tempuri.org/IDuenioService/RegistrarDuenioResponse")]
        void RegistrarDuenio(int dni, string nombre, string apellido, string direccion, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuenioService/RegistrarDuenio", ReplyAction="http://tempuri.org/IDuenioService/RegistrarDuenioResponse")]
        System.Threading.Tasks.Task RegistrarDuenioAsync(int dni, string nombre, string apellido, string direccion, string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuenioService/BuscarDuenio", ReplyAction="http://tempuri.org/IDuenioService/BuscarDuenioResponse")]
        string BuscarDuenio(int dniDuenio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuenioService/BuscarDuenio", ReplyAction="http://tempuri.org/IDuenioService/BuscarDuenioResponse")]
        System.Threading.Tasks.Task<string> BuscarDuenioAsync(int dniDuenio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDuenioServiceChannel : ClienteWinsowsForm.proxyDuenio.IDuenioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DuenioServiceClient : System.ServiceModel.ClientBase<ClienteWinsowsForm.proxyDuenio.IDuenioService>, ClienteWinsowsForm.proxyDuenio.IDuenioService {
        
        public DuenioServiceClient() {
        }
        
        public DuenioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DuenioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DuenioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DuenioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegistrarDuenio(int dni, string nombre, string apellido, string direccion, string telefono) {
            base.Channel.RegistrarDuenio(dni, nombre, apellido, direccion, telefono);
        }
        
        public System.Threading.Tasks.Task RegistrarDuenioAsync(int dni, string nombre, string apellido, string direccion, string telefono) {
            return base.Channel.RegistrarDuenioAsync(dni, nombre, apellido, direccion, telefono);
        }
        
        public string BuscarDuenio(int dniDuenio) {
            return base.Channel.BuscarDuenio(dniDuenio);
        }
        
        public System.Threading.Tasks.Task<string> BuscarDuenioAsync(int dniDuenio) {
            return base.Channel.BuscarDuenioAsync(dniDuenio);
        }
    }
}
