//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWeb.proxyCita {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxyCita.ICitaService")]
    public interface ICitaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICitaService/AsignarCita", ReplyAction="http://tempuri.org/ICitaService/AsignarCitaResponse")]
        string AsignarCita(string horaC, string fechaC, int dniD, string numC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICitaService/AsignarCita", ReplyAction="http://tempuri.org/ICitaService/AsignarCitaResponse")]
        System.Threading.Tasks.Task<string> AsignarCitaAsync(string horaC, string fechaC, int dniD, string numC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICitaServiceChannel : ClienteWeb.proxyCita.ICitaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CitaServiceClient : System.ServiceModel.ClientBase<ClienteWeb.proxyCita.ICitaService>, ClienteWeb.proxyCita.ICitaService {
        
        public CitaServiceClient() {
        }
        
        public CitaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CitaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CitaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CitaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AsignarCita(string horaC, string fechaC, int dniD, string numC) {
            return base.Channel.AsignarCita(horaC, fechaC, dniD, numC);
        }
        
        public System.Threading.Tasks.Task<string> AsignarCitaAsync(string horaC, string fechaC, int dniD, string numC) {
            return base.Channel.AsignarCitaAsync(horaC, fechaC, dniD, numC);
        }
    }
}
