//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWinsowsForm.proxyVeterinario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxyVeterinario.IVeterinarioService")]
    public interface IVeterinarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeterinarioService/AgregarVeterinario", ReplyAction="http://tempuri.org/IVeterinarioService/AgregarVeterinarioResponse")]
        void AgregarVeterinario(string nombre, string apellido, string dni, string telefono, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeterinarioService/AgregarVeterinario", ReplyAction="http://tempuri.org/IVeterinarioService/AgregarVeterinarioResponse")]
        System.Threading.Tasks.Task AgregarVeterinarioAsync(string nombre, string apellido, string dni, string telefono, string direccion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVeterinarioServiceChannel : ClienteWinsowsForm.proxyVeterinario.IVeterinarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VeterinarioServiceClient : System.ServiceModel.ClientBase<ClienteWinsowsForm.proxyVeterinario.IVeterinarioService>, ClienteWinsowsForm.proxyVeterinario.IVeterinarioService {
        
        public VeterinarioServiceClient() {
        }
        
        public VeterinarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VeterinarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VeterinarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VeterinarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AgregarVeterinario(string nombre, string apellido, string dni, string telefono, string direccion) {
            base.Channel.AgregarVeterinario(nombre, apellido, dni, telefono, direccion);
        }
        
        public System.Threading.Tasks.Task AgregarVeterinarioAsync(string nombre, string apellido, string dni, string telefono, string direccion) {
            return base.Channel.AgregarVeterinarioAsync(nombre, apellido, dni, telefono, direccion);
        }
    }
}
