//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWinsowsForm.proxyHistoriaClinica {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxyHistoriaClinica.IHistoriaClinicaService")]
    public interface IHistoriaClinicaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoriaClinicaService/ConsultarHistoria", ReplyAction="http://tempuri.org/IHistoriaClinicaService/ConsultarHistoriaResponse")]
        string ConsultarHistoria(int idMascota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoriaClinicaService/ConsultarHistoria", ReplyAction="http://tempuri.org/IHistoriaClinicaService/ConsultarHistoriaResponse")]
        System.Threading.Tasks.Task<string> ConsultarHistoriaAsync(int idMascota);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHistoriaClinicaServiceChannel : ClienteWinsowsForm.proxyHistoriaClinica.IHistoriaClinicaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HistoriaClinicaServiceClient : System.ServiceModel.ClientBase<ClienteWinsowsForm.proxyHistoriaClinica.IHistoriaClinicaService>, ClienteWinsowsForm.proxyHistoriaClinica.IHistoriaClinicaService {
        
        public HistoriaClinicaServiceClient() {
        }
        
        public HistoriaClinicaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HistoriaClinicaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoriaClinicaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoriaClinicaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConsultarHistoria(int idMascota) {
            return base.Channel.ConsultarHistoria(idMascota);
        }
        
        public System.Threading.Tasks.Task<string> ConsultarHistoriaAsync(int idMascota) {
            return base.Channel.ConsultarHistoriaAsync(idMascota);
        }
    }
}
