//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWinsowsForm.proxyDiagnostico {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxyDiagnostico.IDiagnosticoService")]
    public interface IDiagnosticoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiagnosticoService/AgregarDiagnotico", ReplyAction="http://tempuri.org/IDiagnosticoService/AgregarDiagnoticoResponse")]
        string AgregarDiagnotico(string enfermedad, string Medicina, int dniVeterinario, int idMascota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiagnosticoService/AgregarDiagnotico", ReplyAction="http://tempuri.org/IDiagnosticoService/AgregarDiagnoticoResponse")]
        System.Threading.Tasks.Task<string> AgregarDiagnoticoAsync(string enfermedad, string Medicina, int dniVeterinario, int idMascota);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiagnosticoServiceChannel : ClienteWinsowsForm.proxyDiagnostico.IDiagnosticoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiagnosticoServiceClient : System.ServiceModel.ClientBase<ClienteWinsowsForm.proxyDiagnostico.IDiagnosticoService>, ClienteWinsowsForm.proxyDiagnostico.IDiagnosticoService {
        
        public DiagnosticoServiceClient() {
        }
        
        public DiagnosticoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiagnosticoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiagnosticoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiagnosticoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AgregarDiagnotico(string enfermedad, string Medicina, int dniVeterinario, int idMascota) {
            return base.Channel.AgregarDiagnotico(enfermedad, Medicina, dniVeterinario, idMascota);
        }
        
        public System.Threading.Tasks.Task<string> AgregarDiagnoticoAsync(string enfermedad, string Medicina, int dniVeterinario, int idMascota) {
            return base.Channel.AgregarDiagnoticoAsync(enfermedad, Medicina, dniVeterinario, idMascota);
        }
    }
}
