//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaClinica
    {
        public int idHistoriaClinica { get; set; }
        public string dniDuenio { get; set; }
        public Nullable<int> idDiagnostico { get; set; }
    
        public virtual Diagnostico Diagnostico { get; set; }
    }
}
